/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { CaptionStyle, WordCaption } from './types';

export const COMPONENT_IDS = {
  PRESET_BUTTON: 'preset-btn',
  FONT_SELECTOR: 'font-selector',
  SIZE_SLIDER: 'size-slider',
  COLOR_PICKER: 'color-picker',
  STROKE_TOGGLE: 'stroke-toggle',
  SHADOW_TOGGLE: 'shadow-toggle',
  ANIMATION_SELECTOR: 'animation-selector',
  EXPORT_BUTTON: 'export-button',
  FILE_UPLOAD_AREA: 'file-upload-area',
  MANUAL_CAPTION_EDIT: 'manual-caption-edit',
  PREVIEW_PLAY_PAUSE: 'preview-play-pause',
};

// Royalty-free 9:16 vertical video clip of a person in neon city lights, perfect for testing CapCut viral captions!
export const DEMO_VIDEOS = [
  {
    name: 'Cyberpunk Neon Vibe (9:16 Vertical)',
    url: '/demo-vertical.mp4',
    captions: [
      { text: 'Create', start: 0.1, end: 0.8 },
      { text: 'stunning', start: 0.8, end: 1.4 },
      { text: 'AI', start: 1.4, end: 1.8 },
      { text: 'captions', start: 1.8, end: 2.5 },
      { text: 'directly', start: 2.5, end: 3.2 },
      { text: 'on your', start: 3.2, end: 3.8 },
      { text: 'phone!', start: 3.8, end: 4.8 },
      { text: 'No watermarks,', start: 5.2, end: 6.8 },
      { text: 'instant', start: 6.8, end: 7.5 },
      { text: 'render,', start: 7.5, end: 8.2 },
      { text: 'and viral', start: 8.2, end: 9.0 },
      { text: 'templates', start: 9.0, end: 9.8 },
      { text: 'like custom', start: 9.8, end: 10.6 },
      { text: 'CapCut style.', start: 10.6, end: 11.8 },
      { text: 'Are you ready', start: 12.2, end: 13.5 },
      { text: 'to double', start: 13.5, end: 14.1 },
      { text: 'your engagement?', start: 14.1, end: 15.5 },
      { text: 'Let’s go viral!', start: 15.8, end: 17.5 }
    ] as WordCaption[]
  },
  {
    name: 'Selfie Talk Vlog (Landscape Demo)',
    url: '/demo-landscape.mp4',
    captions: [
      { text: 'Hey guys!', start: 0.2, end: 1.0 },
      { text: 'Check out this', start: 1.1, end: 1.9 },
      { text: 'insane editor.', start: 2.0, end: 3.1 },
      { text: 'It transcribes', start: 3.2, end: 4.2 },
      { text: 'my speech', start: 4.2, end: 5.0 },
      { text: 'automatically', start: 5.0, end: 6.2 },
      { text: 'using Gemini AI.', start: 6.2, end: 7.8 },
      { text: 'I can style it,', start: 8.3, end: 9.5 },
      { text: 'make the words', start: 9.6, end: 10.5 },
      { text: 'bounce,', start: 10.5, end: 11.2 },
      { text: 'change font family,', start: 11.3, end: 12.8 },
      { text: 'and export', start: 13.0, end: 13.8 },
      { text: 'immediately', start: 13.8, end: 14.9 },
      { text: 'to my camera roll.', start: 14.9, end: 16.5 }
    ] as WordCaption[]
  }
];

export const CAPTION_PRESETS: CaptionStyle[] = [
  {
    id: 'classic-viral',
    name: '🔥 Classic Viral',
    fontFamily: 'impact',
    fontSize: 70,
    textColor: '#ffffff',
    useGradient: false,
    strokeColor: '#000000',
    strokeWidth: 8,
    useStroke: true,
    shadowColor: 'transparent',
    shadowBlur: 0,
    shadowOffset: 0,
    useShadow: false,
    bubbleColor: '#000000',
    bubbleOpacity: 0.2,
    useBubble: false,
    letterSpacing: 2,
    lineSpacing: 1.2,
    wordHighlightColor: '#ffffff',
    animationStyle: 'bounce',
    position: 'center',
    customX: 0.5,
    customY: 0.65,
  },
  {
    id: 'tiktok-premium',
    name: '✨ TikTok Premium',
    fontFamily: 'hype',
    fontSize: 72,
    textColor: '#ffffff',
    useGradient: false,
    strokeColor: '#000000',
    strokeWidth: 8,
    useStroke: true,
    shadowColor: 'transparent',
    shadowBlur: 0,
    shadowOffset: 0,
    useShadow: false,
    bubbleColor: '#000000',
    bubbleOpacity: 0.2,
    useBubble: false,
    letterSpacing: 0,
    lineSpacing: 1.1,
    wordHighlightColor: '#facc15', // Yellow highlight on active words
    animationStyle: 'karaoke',
    position: 'center',
    customX: 0.5,
    customY: 0.65,
  },
  {
    id: 'podcast-style',
    name: '🎙️ Podcast Style',
    fontFamily: 'sans',
    fontSize: 50,
    textColor: '#ffffff',
    useGradient: false,
    strokeColor: 'transparent',
    strokeWidth: 0,
    useStroke: false,
    shadowColor: 'transparent',
    shadowBlur: 0,
    shadowOffset: 0,
    useShadow: false,
    bubbleColor: '#000000',
    bubbleOpacity: 0.6, // Semi-transparent black background
    useBubble: true,
    letterSpacing: 1,
    lineSpacing: 1.3,
    wordHighlightColor: '#ffffff',
    animationStyle: 'fadeup',
    position: 'center',
    customX: 0.5,
    customY: 0.75,
  },
  {
    id: 'cinema',
    name: '🎬 Cinema',
    fontFamily: 'cinematic',
    fontSize: 40,
    textColor: '#ffffff',
    useGradient: false,
    strokeColor: 'transparent',
    strokeWidth: 0,
    useStroke: false,
    shadowColor: '#000000',
    shadowBlur: 4,
    shadowOffset: 2, // Thin black shadow
    useShadow: true,
    bubbleColor: 'transparent',
    bubbleOpacity: 0,
    useBubble: false,
    letterSpacing: 4, // Letter spacing
    lineSpacing: 1.4,
    wordHighlightColor: '#ffffff',
    animationStyle: 'typewriter',
    position: 'bottom',
    customX: 0.5,
    customY: 0.85,
  },
  {
    id: 'impact-viral',
    name: '💥 Impact Viral',
    fontFamily: 'impact',
    fontSize: 85, // Large bold font
    textColor: '#ffffff',
    useGradient: false,
    strokeColor: '#000000',
    strokeWidth: 12, // Heavy outline
    useStroke: true,
    shadowColor: '#000000',
    shadowBlur: 10,
    shadowOffset: 4,
    useShadow: true,
    bubbleColor: 'transparent',
    bubbleOpacity: 0,
    useBubble: false,
    letterSpacing: 2,
    lineSpacing: 1.2,
    wordHighlightColor: '#ffffff',
    animationStyle: 'pop', // Pop animation
    position: 'center',
    customX: 0.5,
    customY: 0.65,
  },
  {
    id: 'smoke-reveal',
    name: '💨 Smoke Reveal',
    fontFamily: 'impact',
    fontSize: 75,
    textColor: '#ffffff',
    useGradient: false,
    strokeColor: '#1e293b',
    strokeWidth: 6,
    useStroke: true,
    shadowColor: '#64748b',
    shadowBlur: 15,
    shadowOffset: 0,
    useShadow: true,
    bubbleColor: 'transparent',
    bubbleOpacity: 0,
    useBubble: false,
    letterSpacing: 3,
    lineSpacing: 1.2,
    wordHighlightColor: '#cbd5e1',
    animationStyle: 'smoke',
    position: 'center',
    customX: 0.5,
    customY: 0.65,
  },
  {
    id: 'cyber-glitch',
    name: '⚡ Cyber Glitch',
    fontFamily: 'mono',
    fontSize: 65,
    textColor: '#00ffff',
    useGradient: false,
    strokeColor: '#ff0055',
    strokeWidth: 5,
    useStroke: true,
    shadowColor: '#00ffff',
    shadowBlur: 8,
    shadowOffset: 2,
    useShadow: true,
    bubbleColor: 'transparent',
    bubbleOpacity: 0,
    useBubble: false,
    letterSpacing: 1,
    lineSpacing: 1.2,
    wordHighlightColor: '#ffff00',
    animationStyle: 'glitch',
    position: 'center',
    customX: 0.5,
    customY: 0.65,
  },
  {
    id: 'slanted-skew',
    name: '📐 Slanted Skew',
    fontFamily: 'sans',
    fontSize: 70,
    textColor: '#facc15',
    useGradient: false,
    strokeColor: '#000000',
    strokeWidth: 8,
    useStroke: true,
    shadowColor: 'transparent',
    shadowBlur: 0,
    shadowOffset: 0,
    useShadow: false,
    bubbleColor: 'transparent',
    bubbleOpacity: 0,
    useBubble: false,
    letterSpacing: 0,
    lineSpacing: 1.2,
    wordHighlightColor: '#ffffff',
    animationStyle: 'skew',
    position: 'center',
    customX: 0.5,
    customY: 0.65,
  },
  {
    id: 'elastic-spring',
    name: '🎈 Elastic Spring',
    fontFamily: 'comic',
    fontSize: 75,
    textColor: '#ff6b6b',
    useGradient: false,
    strokeColor: '#ffffff',
    strokeWidth: 6,
    useStroke: true,
    shadowColor: '#ff6b6b',
    shadowBlur: 8,
    shadowOffset: 3,
    useShadow: true,
    bubbleColor: 'transparent',
    bubbleOpacity: 0,
    useBubble: false,
    letterSpacing: 1,
    lineSpacing: 1.2,
    wordHighlightColor: '#ffe066',
    animationStyle: 'elastic',
    position: 'center',
    customX: 0.5,
    customY: 0.65,
  },
  {
    id: '3d-flip-card',
    name: '🔄 3D Flip Card',
    fontFamily: 'hype',
    fontSize: 68,
    textColor: '#ffffff',
    useGradient: false,
    strokeColor: '#000000',
    strokeWidth: 6,
    useStroke: true,
    shadowColor: 'transparent',
    shadowBlur: 0,
    shadowOffset: 0,
    useShadow: false,
    bubbleColor: '#4f46e5',
    bubbleOpacity: 0.9,
    useBubble: true,
    letterSpacing: 2,
    lineSpacing: 1.2,
    wordHighlightColor: '#facc15',
    animationStyle: 'flip',
    position: 'center',
    customX: 0.5,
    customY: 0.65,
  },
  {
    id: 'fire-burner',
    name: '🔥 Fire Burner',
    fontFamily: 'impact',
    fontSize: 80,
    textColor: '#f97316',
    useGradient: false,
    strokeColor: '#000000',
    strokeWidth: 10,
    useStroke: true,
    shadowColor: '#ef4444',
    shadowBlur: 20,
    shadowOffset: 0,
    useShadow: true,
    bubbleColor: 'transparent',
    bubbleOpacity: 0,
    useBubble: false,
    letterSpacing: 1,
    lineSpacing: 1.2,
    wordHighlightColor: '#facc15',
    animationStyle: 'fire',
    position: 'center',
    customX: 0.5,
    customY: 0.65,
  },
  {
    id: 'hurricane-spin',
    name: '🌀 Hurricane Spin',
    fontFamily: 'hype',
    fontSize: 75,
    textColor: '#3b82f6',
    useGradient: false,
    strokeColor: '#ffffff',
    strokeWidth: 6,
    useStroke: true,
    shadowColor: '#1d4ed8',
    shadowBlur: 10,
    shadowOffset: 2,
    useShadow: true,
    bubbleColor: 'transparent',
    bubbleOpacity: 0,
    useBubble: false,
    letterSpacing: 2,
    lineSpacing: 1.2,
    wordHighlightColor: '#60a5fa',
    animationStyle: 'spin',
    position: 'center',
    customX: 0.5,
    customY: 0.65,
  },
  {
    id: 'split-slide-in',
    name: '↔️ Split Slide-In',
    fontFamily: 'sans',
    fontSize: 70,
    textColor: '#ec4899',
    useGradient: false,
    strokeColor: '#000000',
    strokeWidth: 8,
    useStroke: true,
    shadowColor: 'transparent',
    shadowBlur: 0,
    shadowOffset: 0,
    useShadow: false,
    bubbleColor: 'transparent',
    bubbleOpacity: 0,
    useBubble: false,
    letterSpacing: 1,
    lineSpacing: 1.2,
    wordHighlightColor: '#ffffff',
    animationStyle: 'slideSplit',
    position: 'center',
    customX: 0.5,
    customY: 0.65,
  },
  {
    id: 'cosmic-rainbow',
    name: '🌈 Cosmic Rainbow',
    fontFamily: 'impact',
    fontSize: 85,
    textColor: '#ffffff',
    useGradient: false,
    strokeColor: '#000000',
    strokeWidth: 10,
    useStroke: true,
    shadowColor: '#4f46e5',
    shadowBlur: 12,
    shadowOffset: 3,
    useShadow: true,
    bubbleColor: 'transparent',
    bubbleOpacity: 0,
    useBubble: false,
    letterSpacing: 2,
    lineSpacing: 1.2,
    wordHighlightColor: '#10b981',
    animationStyle: 'rainbow',
    position: 'center',
    customX: 0.5,
    customY: 0.65,
  },
  {
    id: 'heartbeat-beat',
    name: '💓 Heartbeat Beat',
    fontFamily: 'comic',
    fontSize: 75,
    textColor: '#ef4444',
    useGradient: false,
    strokeColor: '#ffffff',
    strokeWidth: 6,
    useStroke: true,
    shadowColor: '#ef4444',
    shadowBlur: 15,
    shadowOffset: 0,
    useShadow: true,
    bubbleColor: 'transparent',
    bubbleOpacity: 0,
    useBubble: false,
    letterSpacing: 0,
    lineSpacing: 1.2,
    wordHighlightColor: '#facc15',
    animationStyle: 'heartbeat',
    position: 'center',
    customX: 0.5,
    customY: 0.65,
  }
];

export const FONT_PAIRS = {
  sans: '"Inter", system-ui, -apple-system, sans-serif',
  impact: '"Montserrat", "Impact", "Arial Black", sans-serif',
  cinematic: '"Lora", Georgia, serif',
  comic: '"Fredoka", "Comic Neue", cursive',
  hype: '"Lilita One", sans-serif',
  mono: '"JetBrains Mono", monospace',
};
